export const endpoints = {
  auth: {
    login: '/login',
    register: '/register',
    logout: '/logOut',
    token: '/token',
    forgotPassword: '/reset/password/search',
    verifyCode: '/reset/password/final',
    resetPassword: '/reset/password/change',
  },
  posts: {
    list: '/posts',
    create: '/posts/create',
    get: (id: string) => `/posts/get/${id}`,
    edit: (id: string) => `/posts/edit/${id}`,
    delete: (id: string) => `/posts/delete/${id}`,
    like: (userId: string, postId: string) => `/like/${userId}/${postId}`,
    unlike: (userId: string, postId: string) => `/unlike/${userId}/${postId}`,
  },
  comments: {
    list: (userId: string, postId: string) => `/comment/${userId}/${postId}`,
    create: (userId: string, postId: string) => `/comment/${userId}/${postId}`,
    edit: (userId: string, postId: string, commentId: string) => `/comment/${userId}/${postId}/${commentId}`,
    delete: (userId: string, postId: string, commentId: string) => `/comment/${userId}/${postId}/${commentId}`,
  },
  users: {
    profile: (userId: string) => `/users/${userId}`,
    me: '/users/me',
    edit: '/users/profile/edit',
    profilePicture: '/users/profilePicture',
    follow: (userId: string) => `/follow/${userId}`,
    unfollow: (userId: string) => `/unfollow/${userId}`,
    followers: (userId: string) => `/followers/${userId}`,
    following: (userId: string) => `/following/${userId}`,
  },
  search: {
    users: '/search/users',
    posts: '/search/posts',
  },
  feed: '/feed',
};